- include_vars: main_vars.yml

- include_vars: "{{ ansible_os_family }}_vars.yml"

- name: Install Bind9
  include_tasks: install_bind9.yml

- name: Set needed facts
  include_tasks: set_facts.yml

- name: Configure DNS Cache
  include_tasks: configure_options.yml
  when: bind_is_master == True
  
- name: Configure DNS Master
  include_tasks: configure_master.yml
  when: bind_is_master == True

- name: Configure DNS Slave
  include_tasks: configure_slave.yml
  when: bind_is_master == False and bind_is_slave == True
  
- name: Ensure bind9 is started and enabled at boot
  service: 
    name={{ bind_service }}
    state=restarted
    enabled=yes
